exemplo2/blue_mvc/models/__init__.py
__all__ =[
        'user',
        'esporte'
]

exemplo2/blue_mvc/models/esportes.py
from database import get_connection

class Esporte:
    def __init__(self, nome,user_id):
        self.nome = nome
        self.user_id = user_id
        
    def save(self):
        conn = get_connection()
        conn.execute("INSERT INTO esportes(nome,user_id) values(?,?)", (self.nome,self.user_id))
        conn.commit()
        conn.close()
        return True
    
    @classmethod
    def all(cls):
        conn = get_connection()
        users = conn.execute("SELECT * FROM esportes").fetchall()
        return users

exemplo2/blue_mvc/models/user.py
from database import get_connection

class User:
    def __init__(self,nome) :
        self.nome = nome
    def save(self):
        conn = get_connection()
        conn.execute("INSERT INTO users(nome) VALUES (?)",(self.nome,))
        conn.commit()
        conn.close()
        return True
    @classmethod
    def all(cls):
        conn = get_connection()
        users = conn.execute('SELECT * FROM users').fetchall()
        conn.close()
        return users 

exemplo2/blue_mvc/app.py
from flask import Flask, render_template
from controllers import users,esportes

app = Flask(__name__)
app.register_blueprint(users.bp)
app.register_blueprint(esportes.bp)

@app.route('/')
def index():
          return render_template('index.html')

exemplo2/blue_mvc/controllers/__init__.py
all = [
    
    'users',
    'esportes',
    'auth'
]

exemplo2/blue_mvc/controllers/esportes.py
from flask import Flask, render_template, url_for, request, Blueprint, redirect
from models.user import User
from models.esportes import Esporte

bp = Blueprint('esportes',__name__, url_prefix='/esportes', template_folder='templates')

@bp.route('/')
def index():
    return render_template('esportes/index.html',esportes= Esporte.all())

@bp.route('/registro',methods=['POST','GET'])
def register():
    if request.method=='POST':
        nome = request.form['nome']
        user= request.form['user']

        esporte = Esporte(nome,user)
        Esporte.save(esporte)
        
        return redirect(url_for('esportes.index'))
    return render_template('esportes/register.html',user=User.all())

exemplo2/blue_mvc/controllers/users.py
from flask import render_template, Blueprint, url_for, request, redirect
from models.user import User

bp = Blueprint('users',__name__, url_prefix='/users', template_folder='templates')

@bp.route('/')
def index():
    return render_template('users/index.html',users=User.all())

@bp.route('/register',methods=['GET','POST'])
def register():
    if request.method == 'POST':
        nome = request.form['nome']
        user = User(nome)
        User.save(user)
        return redirect(url_for('users.index'))
    return render_template('users/register.html')

exemplo2/blue_mvc/database/__init__.py
import sqlite3
import os

DATABASE = 'database.db'
dirname = os.path.dirname(os.path.realpath(__file__))

def get_connection():    
    conn = sqlite3.connect(os.path.join(dirname, DATABASE))
    conn.row_factory = sqlite3.Row
    return conn

exemplo2/blue_mvc/templates/esportes/index.html
'<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <h1>Testando página inicial de esportes</h1>
    <a href="{{url_for('esportes.register')}}">Registro de esportes</a>
    <h3>Lista de esportes</h3>
    <ul>
        {% for esporte in esportes %}
        <li>
            <p>{{esporte.nome}}</p>
        </li>
        {% endfor %}
    </ul>
</body>
</html>

exemplo2/blue_mvc/templates/esportes/register.html
'<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <div class="nav"><h1>Registro de Esportes</h1></div>
    <div>
        <div class='main'>
            
        <form action="{{url_for('esportes.register')}}" method="post">
            <h2>Dados</h2>
            <input type="text" name="nome" placeholder="nome" >
            <select name="user" id="user">
                {%for usr in user %}
                <option value="{{usr.id}}">{{usr.nome}}</option>
                {% endfor %}
            </select>
    
            
            <button>Enviar</button>
        </form>
    </div>
    
    </div>
</body>
</html>

exemplo2/blue_mvc/templates/index.html

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <h1>Página inicial</h1>

    <a href="/users"><button>
        usuários
    </button></a>
    <a href="/esportes"><button>
        esportes
    </button></a>

</body>
</html>

exemplo2/blue_mvc/templates/users/index.html
'<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <h1>Testando página inicial de usuários</h1>
    <a href="{{url_for('users.register')}}">Registro de usuários</a>
    <h3>Lista de usuários</h3>
    <ul>

        {% for user in users %}
        <li>
            <p>{{user.nome}}</p>
        </li>
        {% endfor %}
    </ul>
</body>
</html>

exemplo2/blue_mvc/templates/users/register.html
'<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <div class="nav"><h1>Registro de Usuários</h1></div>
    <div>
        <div class='main'>
            
        <form action="{{url_for('users.register')}}" method="post">
            <h2>Dados</h2>
            <input type="email" name="email" placeholder="Email" value="{{request.form['email']}}">
            {% with error = get_flashed_messages()  %}
            <span class="warning">{{error[0]}}</span>    
            {% endwith %}    
            <input type="text" name="nome" placeholder="Nome" value="{{request.form['nome']}}">
            <button>Enviar</button>
        </form>
    </div>
    
    </div>
</body>
</html>