exemplo/case2/models/__init__.py

__all__ = [
    'user',
    'book'
]

exemplo/case2/models/book.py
from database import get_connection

class Book:
    def __init__(self, titulo, user_id):
        self.titulo = titulo
        self.user_id = user_id

    def save(self):
        conn = get_connection()
        conn.execute("INSERT INTO books(titulo, user_id) values(?,?)", (self.titulo, self.user_id))
        conn.commit()
        conn.close()
        return True

    @classmethod
    def all(cls):
        conn = get_connection()
        books = conn.execute("SELECT * FROM books").fetchall()
        return books

exemplo/case2/models/emprestimos.py
from database import get_connection

class Emprestimo():
    def __init__(self, data, user_id, book_id):
        self.data = data
        self.user_id = user_id
        self.book_id = book_id
    
    @classmethod
    def save(cls, data, user_id, book_id):
        conn = get_connection()
        
        conn.execute("INSERT INTO emprestimos (data_emp, user_id, book_id) VALUES (?,?,?)",(data, user_id, book_id))
        conn.commit()
       
        conn.close()
    
    @classmethod
    def all(cls):
        conn = get_connection()
        
        
        emprestimos = conn.execute("SELECT * FROM emprestimos").fetchall()
        
        conn.close()
        return emprestimos

exemplo/case2/models/user.py
from database import get_connection

class User:
    def __init__(self, nome, email):
        self.nome = nome
        self.email = email
        
    def save(self):
        conn = get_connection()
        conn.execute("INSERT INTO users(email, nome) values(?,?)", (self.email, self.nome))
        conn.commit()
        conn.close()
        return True
    
    @classmethod
    def all(cls):
        conn = get_connection()
        users = conn.execute("SELECT * FROM users").fetchall()
        return users

exemplo/case2/app.py
from flask import Flask, render_template
from controllers import users, books, emprestimos 

app = Flask(__name__)
app.register_blueprint(users.bp)
app.register_blueprint(books.bp)
app.register_blueprint(emprestimos.bp)

@app.route('/')
def index():
    return render_template('index.html')

exemplo/case2/controllers/__init__.py

all = [
    'books',
    'users',
    'emprestimos'
]

exemplo/case2/controllers/books.py
from flask import Flask, render_template, url_for, request, Blueprint, redirect
from models.user import User
from models.book import Book

bp = Blueprint('books', __name__, url_prefix='/books', static_folder='static/..')

@bp.route('/')
def index():
    return render_template('books/index.html', books = Book.all())

@bp.route('/register', methods=['POST', 'GET'])
def register():
    
    if request.method == 'POST':
        titulo = request.form['titulo']
        user = request.form['user']

        book = Book(titulo, user)
        book.save()
        return redirect(url_for('books.index'))


    return render_template('books/register.html', users=User.all())

exemplo/case2/controllers/emprestimos.py
from flask import Flask, render_template, redirect, url_for, request, Blueprint
from models.user import User
from models.book import Book
from models.emprestimos import Emprestimo




bp = Blueprint('emprestimos', __name__, url_prefix='/emprestimos', template_folder='templates')

@bp.route('/')
def index():
    return render_template('emprestimos/index.html',emprestimos=Emprestimo.all())

@bp.route('/register', methods=['POST', 'GET'])
def register():

    if request.method == 'POST':
        data = request.form['data']
        user = request.form['user']
        book = request.form['book']
        Emprestimo.save(data, user, book)

       
        
        return redirect(url_for('emprestimos.index' ))


    return render_template('emprestimos/register.html', users=User.all(), books = Book.all())

exemplo/case2/controllers/users.py
from flask import render_template, Blueprint, url_for, request, flash, redirect
from models.user import User

# módulo de usuários
bp = Blueprint('users', __name__, url_prefix='/users')

@bp.route('/')
def index():
    return render_template('users/index.html', users = User.all())

@bp.route('/register', methods=['POST', 'GET'])
def register():
    if request.method == 'POST':
        email = request.form['email']
        nome= request.form['nome']

        if not email:
            flash('Email é obrigatório')
        else:
            user = User(email, nome)
            user.save()
            return redirect(url_for('users.index'))
    
    return render_template('users/register.html')

exemplo/case2/templates/books/index.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
    
    <style>
        h1{
            color: wheat;
            
        }
       
        .nav{
            background-color: brown;
            display: flex;
            justify-content: center;
            padding: 10px;
        }
        .main{
            
            display: flex;
            flex-direction: column;
            align-items: right;
            
            width: 100%;
            
        }
        .main a{
            width: 10%;
        }
        button{
            width: 10%;
            height: 40px;
            margin-top: 15px;
            margin-left:85%;
            border-radius: 10px;
            border: 4px solid brown;
            background-color: wheat;
            
        }
        button:hover{
            background-color:brown;
            color:white;
        }
        .main ul{
            width:30%;
            color:white;
        }
        .main p{
            color:brown;
            padding:10px;
            height:30px;
            border:0.5px solid;
            width:100%;
            background-color:wheat;
        }
    </style>
</head>
<body>

    <div class="nav"><h1>Lista de Livros</h1></div>


    <a href="{{url_for('books.register')}}"><button>Adicionar</button></a>
    <div class='main'>
    <hr>
    <ul>
    {% for book in books %}
    <li><p>{{book.titulo}}</p></li>
    {% endfor %}
    </ul>
    </div>
    
    
</body>
</html>

exemplo/case2/templates/books/register.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Books - Register</title>
    <link rel="stylesheet" href="{{ url_for('static', filename='books/style.css') }}">
    
</head>
<body>

    <div class='nav'><h1>Registrar Livros</h1></div>
    <div class='main'>
    <div>
        
        <form action="{{url_for('books.register')}}" method="post">
            <h2>Dados</h2>
            <input type="text" name="titulo" placeholder="Título" value="{{request.form['titulo']}}">
            <select name="user">
                {% for user in users %}
                    <option value="{{user.id}}">{{user.nome}}</option>    
                {% endfor %}                
            </select>
            <button>Enviar</button>
        </form>
    </div>
    </div>


    
</body>
</html>

exemplo/case2/templates/emprestimos/index.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
    <style>
        h1{
            color: wheat;
            
        }
       
        .nav{
            background-color: brown;
            display: flex;
            justify-content: center;
            padding: 10px;
        }
        .main{
            
            display: flex;
            flex-direction: column;
            align-items: right;
            
            width: 100%;
            
        }
        .main a{
            width: 10%;
        }
        button{
            width: 10%;
            height: 40px;
            margin-top: 15px;
            margin-left:85%;
            border-radius: 10px;
            border: 4px solid brown;
            background-color: wheat;
            
        }
        button:hover{
            background-color:brown;
            color:white;
        }
        .main ul{
            width:30%;
            color:white;
        }
        .main p{
            color:brown;
            padding:10px;
            height:30px;
            border:0.5px solid;
            width:100%;
            background-color:wheat;
        }
    </style>
</head>
<body>
   <div class="nav"><h1>Emprestimos</h1></div>
   <a href="{{url_for('emprestimos.register')}}"><button>Adicionar</button></a>
   <div class='main'>
   <ul>
    {%for emp in emprestimos%}
    
    <li><p>Emprestimo na data {{emp[1]}}</p></li>
    {%endfor%}
    
    
   </ul>
    </div>
</body>
</html>

exemplo/case2/templates/emprestimos/register.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
    <style>
        h1{
            color: wheat;
            
        }
        
       
        .nav{
            background-color: brown;
            display: flex;
            justify-content: center;
            padding: 20px;
        }
        form{
            width:100%;
            display:flex;
            flex-direction:column;
            justify-content:center;
            height:80vh;
            align-items:center;
            
        }
        form input, button, select{
            width:25%;
            background-color:wheat;
            border: 2px solid brown;
            margin-bottom:10px;
            height:30px;
        }
        form button{
            width:10%;
            height:40px;
            border:3px solid brown;
            border-radius:20px;
        }
        form button:hover{
            background-color:brown;
            color:white;
        }
    </style>
</head>
<body>
    <div class='nav'><h1>Registro de usuários</h1></div>
    <div class='main'>
    <form action="{{url_for('emprestimos.register')}}" method="post">
        <input type="date" placeholder="Data do emprestimo" name="data">
        
        <select name="user" id="user">
            {% for user in users %}
            <option value="{{user[0]}}">{{user[1]}}</option>
            {% endfor %}
        </select>

        <select name="book" id="book">
            {% for book in books %}
            <option value="{{book[0]}}">{{book[1]}}</option>
            {% endfor %}
        </select>
        
        <button>Enviar</button>
    </form>
    </div>
</body>
</html>

exemplo/case2/templates/index.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
    
    <style>
        h1{
            color: wheat;
            display: flex;
            justify-content: center;
            padding: 20px;
        }
        body{
            
            margin: 0;
            padding: 0;
        }
        .nav{
            background-color: brown;
        }
        .main{
            margin-top: 10%;
            display: flex;
            flex-direction: column;
            align-items: center;
            justify-content: center;
            width: 100%;
            
        }
        .main a{
            width: 25%;
        }
        .main button{
            width: 100%;
            height: 35px;
            margin-bottom: 15px;
            border-radius: 10px;
            border: 4px solid brown;
            background-color: wheat
        }
    </style>
</head>
<body>
    <div class="nav">
        <h1>Sistema Biblioteca</h1>
        
    </div>
       <div class="main">
        <a href="/users"><button>Usuários</button></a>
        <a href="/books"><button>Livros</button></a>
        <a href="/emprestimos"><button>Emprestimos</button></a>
       </div>
</body>
</html>

exemplo/case2/templates/users/index.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
    <link rel="stylesheet" href="users/style.css">
    <style>
        h1{
            color: wheat;
            
        }
       
        .nav{
            background-color: brown;
            display: flex;
            justify-content: center;
            padding: 10px;
        }
        .main{
            
            display: flex;
            flex-direction: column;
            align-items: right;
            
            width: 100%;
            
        }
        .main a{
            width: 10%;
        }
        button{
            width: 10%;
            height: 40px;
            margin-top: 15px;
            margin-left:85%;
            border-radius: 10px;
            border: 4px solid brown;
            background-color: wheat;
            
        }
        button:hover{
            background-color:brown;
            color:white;
        }
        .main ul{
            width:30%;
            color:white;
        }
        .main p{
            color:brown;
            padding:10px;
            height:30px;
            border:0.5px solid;
            width:100%;
            background-color:wheat;
        }
    </style>
</head>
<body>
    
    <div class="nav"><h1>Lista de Usuários</h1></div>
    <a href="{{url_for('users.register')}}"><button>Adicionar</button></a>
    <div class='main'>
    <hr>
    <ul>
    {% for user in users %}
    <li><p>{{user.nome}}</p></li>
    {% endfor %}
    </ul>
    </div>
    
</body>
</html>

exemplo/case2/templates/users/register.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
    
    <style>
        h1{
            color: wheat;
            
        }
        
        .nav{
            background-color: brown;
            display: flex;
            justify-content: center;
            padding: 20px;
        }
        form{
            width:100%;
            display:flex;
            flex-direction:column;
            align-items: center;
            justify-content:center;
            
        }
        form input, button{
            width:25%;
            background-color:wheat;
            border: 2px solid brown;
            margin-bottom:10px;
            height:30px;
        }
        form button{
            width:10%;
            height:40px;
            border:3px solid brown;
            border-radius:20px;
        }
        form button:hover{
            background-color:brown;
            color:white;
        }
        
       
    </style>
</head>
<body>
    
    <div class="nav"><h1>Registro de Usuários</h1></div>
    <div>
        <div class='main'>
            
        <form action="{{url_for('users.register')}}" method="post">
            <h2>Dados</h2>
            <input type="email" name="email" placeholder="Email" value="{{request.form['email']}}">
            {% with error = get_flashed_messages()  %}
            <span class="warning">{{error[0]}}</span>    
            {% endwith %}    
            <input type="text" name="nome" placeholder="Nome" value="{{request.form['nome']}}">
            <button>Enviar</button>
        </form>
    </div>
    
    </div>

</body>
</html>

exemplo/case2/templates/users/teste.html
{% extends 'layout.html' %}

{% block content %}
    <h1>Oi</h1>
{% endblock %}